# golangci-lint configuration
version: 2

run:
  timeout: 5m
  go: "1.24.1"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - misspell
    - errname
    - errorlint
    - unconvert
    - unparam
  disable:
    - errcheck

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - singleCaseSwitch
      - hugeParam
      - rangeValCopy
      - octalLiteral

  staticcheck:
    checks: ["all"]

  gocyclo:
    min-complexity: 30

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 