builds:
  - main: ./cmd/flow
    binary: flow
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "canary-{{ .ShortCommit }}"

release:
  prerelease: auto
