repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: local
  hooks:
    - id: make-check
      name: make check
      description: Run comprehensive code quality checks using make check.
      entry: make check
      language: system
      types: [go]
      pass_filenames: false 